print("Presentscion: Edw_09")
print("")
print("Nombre Completo: ")
print("Edward Leonaedo Viveros Uribe ")
print("")
print("Fortslezas: ")
print("1.-Aprendo Rapido")
print("2.-Se escuchar a las demas personas")
print("3.-Soy algo empatico")
print("")
print("Debilidades: ")
print("1.-Hablo mucho")
print("2.-Me distraigo con facilidad")
print("3.-Soy muy flojo")
print("")
print("Logros: ")
print("1.-Salir de la secundaria")
print("2.-Entrar a la prepa")
print("3.-saber programar un poco")
print("")
print("Musica y Artistas favoritos: ")
print("Artistas:")
print("1.-Tito Doublep P")
print("2.-Puré Negga")
print("3.-Junior H")
print("Musica: ")
print("1.-Regge")
print("2.-Rap")
print("3.-Corridos Tmbados")
print("")
print("Vacaciones: ")
print("En mis vacaciones yo le ayude a mi papá con su mudanza, jugué free fire, Clash royal, bralw stars y por último hice ejercicio")